/* tslint:disable */
/* eslint-disable */
/**
 * Greeting API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';


/**
 * GreetingApi - axios parameter creator
 * @export
 */
export const GreetingApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} [name] defaults to World if not given
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGreeting: async (name?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/hello`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GreetingApi - functional programming interface
 * @export
 */
export const GreetingApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GreetingApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} [name] defaults to World if not given
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getGreeting(name?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getGreeting(name, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * GreetingApi - factory interface
 * @export
 */
export const GreetingApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GreetingApiFp(configuration)
    return {
        /**
         * 
         * @param {string} [name] defaults to World if not given
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGreeting(name?: string, options?: any): AxiosPromise<string> {
            return localVarFp.getGreeting(name, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GreetingApi - object-oriented interface
 * @export
 * @class GreetingApi
 * @extends {BaseAPI}
 */
export class GreetingApi extends BaseAPI {
    /**
     * 
     * @param {string} [name] defaults to World if not given
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GreetingApi
     */
    public getGreeting(name?: string, options?: AxiosRequestConfig) {
        return GreetingApiFp(this.configuration).getGreeting(name, options).then((request) => request(this.axios, this.basePath));
    }
}


